apiVersion: apps/v1
kind: Deployment
metadata:
 name: customerapp
 labels:
   app: customerapp
spec:
 replicas: 2
 selector:
   matchLabels:
    app: customerapp
 template:
    metadata:
      name:  customerapp-pod
      labels:
        app: customerapp
        tier: dev
    spec:
      containers:
      - name: customerapp
        image: nrekapalli189/myproject1
        name: latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: customerapp
spec:
  type: LoadBalancer
  selector:
    app: customerapp

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
