apiVersion: apps/v1
kind: Deployment
metadata:
 name: javawebapp
 labels:
   app: javawebapp
spec:
 replicas: 2
 selector:
   matchLabels:
    app: javawebapp
 template:
    metadata:
      name:  javawebapp-pod
      labels:
        app: javawebapp
        tier: dev
    spec:
      containers:
      - name: javawebapp
        image: nrekapalli189/myproject1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: LoadBalancer
  selector:
    app: javawebapp

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
